#include "../src/motion_shaders.hpp"

#include <windows.h>
#include <d3dcompiler.h>
#include <cstdio>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iterator>
#include <sstream>
#include <string>
#include <system_error>

namespace
{
    struct blob
    {
        ID3DBlob *value = nullptr;
        ~blob() { if (value != nullptr) value->Release(); }
    };

    bool append_shader(std::ostringstream &header, const char *source,
        const char *compiler_name, const char *symbol)
    {
        blob bytecode, diagnostics;
        const HRESULT result = D3DCompile(source, std::strlen(source), compiler_name,
            nullptr, nullptr, "main", "ps_3_0", D3DCOMPILE_OPTIMIZATION_LEVEL3, 0,
            &bytecode.value, &diagnostics.value);
        if (diagnostics.value != nullptr)
            std::fputs(static_cast<const char *>(diagnostics.value->GetBufferPointer()), stderr);
        if (FAILED(result) || bytecode.value == nullptr)
        {
            std::fprintf(stderr, "Failed to compile %s: HRESULT 0x%08lX\n", compiler_name,
                static_cast<unsigned long>(result));
            return false;
        }
        const std::size_t byte_count = bytecode.value->GetBufferSize();
        if (byte_count == 0 || byte_count % sizeof(DWORD) != 0)
        {
            std::fprintf(stderr, "Invalid bytecode length for %s\n", compiler_name);
            return false;
        }
        const auto *words = static_cast<const DWORD *>(bytecode.value->GetBufferPointer());
        const std::size_t word_count = byte_count / sizeof(DWORD);
        header << "    alignas(DWORD) inline constexpr DWORD " << symbol << "[] = {\n";
        for (std::size_t index = 0; index < word_count; ++index)
        {
            if (index % 8 == 0) header << "        ";
            header << "0x" << std::hex << std::setw(8) << std::setfill('0') << words[index] << 'u';
            if (index + 1 != word_count) header << ',';
            header << (index % 8 == 7 || index + 1 == word_count ? "\n" : " ");
        }
        header << "    };\n\n";
        std::printf("Compiled %s: %lu bytes\n", symbol, static_cast<unsigned long>(byte_count));
        return true;
    }

    int generate(const std::filesystem::path &path)
    {
        std::ostringstream header;
        header << "// Generated by tools/compile_motion_shaders.cpp. Do not edit.\n"
            "#pragma once\n\n#include <windows.h>\n\nnamespace enr::motion_bytecode\n{\n";
        using namespace enr::motion_shader_source;
        if (!append_shader(header, downsample_source, "ENR motion prefilter", "prefilter") ||
            !append_shader(header, coarse_source, "ENR motion coarse", "coarse") ||
            !append_shader(header, refine_source, "ENR motion refine", "refine")) return 1;
        header << "}\n";
        const std::string contents = header.str();

        std::ifstream existing(path, std::ios::binary);
        if (existing)
        {
            const std::string previous{std::istreambuf_iterator<char>(existing), std::istreambuf_iterator<char>()};
            if (existing.bad())
            {
                std::fprintf(stderr, "Failed to read existing generated shader header\n");
                return 1;
            }
            if (previous == contents) return 0; // Preserve timestamps on identical output.
        }
        existing.close();
        if (!path.parent_path().empty())
        {
            std::error_code error;
            std::filesystem::create_directories(path.parent_path(), error);
            if (error)
            {
                std::fprintf(stderr, "Failed to create shader output directory: %s\n", error.message().c_str());
                return 1;
            }
        }
        std::ofstream output(path, std::ios::binary | std::ios::trunc);
        output.write(contents.data(), static_cast<std::streamsize>(contents.size()));
        output.close();
        if (!output)
        {
            std::fprintf(stderr, "Failed to write generated shader header\n");
            return 1;
        }
        return 0;
    }
}

int main(int argc, char **argv)
{
    if (argc != 2)
    {
        std::fprintf(stderr, "Usage: compile_motion_shaders <output-header>\n");
        return 2;
    }
    try { return generate(std::filesystem::path(argv[1])); }
    catch (const std::exception &error)
    {
        std::fprintf(stderr, "Motion shader generation failed: %s\n", error.what());
        return 1;
    }
}
